### ISSUE TITLE
[Version Compatibility] Minecraft 1.21.0

### ISSUE THREAD

**Issue by heide-oficial** [Lanfix8/AllHUDBars#1]
Any chance we can get this mod for 1.21.0? I hate having more then 20 health ainda seeing more red hearts above my "normal heart bar",and this mod is the perfect solution (and the HUD looks awesome). My modpack with more than 300 mods have some very important mods that are only available for 1.21.0, so I can't really update for 1.21.1.

Thanks!

**Comment by Lanfix8** [comment]
Hello, sorry for the time it takes me to answer and work on the project, I am very busy with my studies at the moment.
As you can see, I created the 1.21 version.
It is already published on [modrinth](https://modrinth.com/mod/all-hud-bars/version/BGpG4zRW) and it is being reviewed on [curseforge](https://www.curseforge.com/minecraft/mc-mods/all-hud-bars)
Thanks for your participation and have fun playing around with my mod !
